name: PR

on: pull_request

jobs:
  build:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Action
        uses: wearerequired/lint-action@v1.9.0
