
name: PR

on: pull_request

jobs:
  build:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint --fix
      - name: Run tests
        run: yarn jest
